### PR TITLE
HAAR-2524: role rename for authorize end point, plus new role to existing Auth OAuth client

### PR DESCRIPTION
**Pull request by AlTurner-MOJ**

### CODE REVIEW

**Comment by nwilliamsmoj** [comment]
Is the new role proxy specific? If so, it may be worth adding that to the name for clarity?

**Comment by nwilliamsmoj** [comment]
When do we generate a new token for the proxying and ow long does it last?

**Comment by AlTurner-MOJ** [comment]
> Is the new role proxy specific? If so, it may be worth adding that to the name for clarity?

The new role is called ROLE_OAUTH_AUTHORIZE. The intention is that it will only be used by the proxy in Auth to call the /authorize end point, which is why I included AUTHORIZE in the role name. Happy to re-name it - please suggest your preferred name for it

**Comment by AlTurner-MOJ** [comment]
> When do we generate a new token for the proxying and ow long does it last?

Good point. The clients we have at the moment are only registered in the DEV environment, but I have raised a separate ticket to look at token time to live for all DEV clients as I think all of those set up on the new authorization server have not been given long enough. HAAR-2568 refers.

**Comment by nwilliamsmoj** [comment]
Could we use ROLE_PROXY_OAUTH_AUTHORIZE.

I know I'm being pedantic, but just trying to ensure that in the future devs will have no doubt that this is for the proxy endpoint only and nothing else.

**Comment by AlTurner-MOJ** [comment]
> Could we use ROLE_PROXY_OAUTH_AUTHORIZE.
> 
> I know I'm being pedantic, but just trying to ensure that in the future devs will have no doubt that this is for the proxy endpoint only and nothing else.

Happy to change the name as you suggest, but I don't think it will really have the desired effect. The term PROXY does not really stand out in the Auth code base as a concept at the moment. The implementation of what we are calling the PROXY in Auth is actually split between a filter (for the `/oauth/token` end point) and a controller (for the `/oauth/authorize` end points),  it has not been packaged a cohesive separate module. Maybe that is something we need to address too, but would prefer to do that as a separate ticket if we agree it is necessary. The purpose of this role is simply to lock down usage of the `/oauth2/authorize` end point in the new authorization server to just Auth, but obviously the role could in theory be allocated to any service. I don't think there is anything we can do to prevent that.

**Comment by nwilliamsmoj** [comment]
Yeah - perhaps I was too fixated on proxying :)

**Review by nwilliamsmoj — APPROVED** [review]

**Pull request merged**
